[package]
name = "highway_hash"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "highway_hash"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
highway = "0.8.1"
